function ClassicApply()
	SKIN:Bang('!WriteKeyValue Variables MorningWP "#@#Wallpapers\\Classic\\Morning.jpg" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables NoonWP "#@#Wallpapers\\Classic\\Noon.jpg" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables AfternoonWP "#@#Wallpapers\\Classic\\Afternoon.jpg" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables EveningWP "#@#Wallpapers\\Classic\\Evening.jpg" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables NightWP "#@#Wallpapers\\Classic\\Night.jpg" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables MColor "0,46,60" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables NColor "166,93,25" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables AColor "255,255,255" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables EColor "218,160,99" "#@#variables.inc"')
	SKIN:Bang('!WriteKeyValue Variables NTColor "199,139,224" "#@#variables.inc"')
end