[Variables]
Author=Evans Stenakis
Name=System Variables
Version=Tropical
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0

;[DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING]

MColor=114,86,115
NColor=72,119,135
AColor=85,145,107
EColor=194,86,48
NTColor=136,51,110
Accent=72,119,135
CMode=250,250,250
OMode=50,50,50
Plugin=ActionTimer        
Mode=0
MusicFont=Google sans
Font=Sailors
Music=WebNowPlaying.dll
AudioPlayerName=WebPlayer
