[Variables]
Author=Evans Stenakis
Name=Variables
Version=Final
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0

;;--------------------------------------------


BE CAREFUL NOT TO CHANGE THE VARIABLES NAMES


;;----------Profile picture and name----------

UserImagePath=C:\Users\ervan\Desktop\New Logo.jpg
UserName=evans

;;----------Wallpapers Directories----------

MorningWP=#@#Wallpapers\Flat\Morning.jpg
NoonWP=#@#Wallpapers\Flat\Noon.jpg
AfternoonWP=#@#Wallpapers\Flat\Afternoon.jpg
EveningWP=#@#Wallpapers\Flat\Evening.jpg
NightWP=#@#Wallpapers\Flat\Night.jpg

;;----------Time Stamps----------

MorningHour=05
NoonHour=12
AfternoonHour=16
EveningHour=19
NightHour=23

;;----------Quotes----------

Morning=Good Morning
Noon=Good Noon
Afternoon=Good Afternoon
Evening=Good Evening
Night=Good Night

;;----------Shortcuts Directories----------

Icon1Path=C:\Users\ervan\AppData\Roaming\Spotify\Spotify.exe
Icon2Path=C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
Icon3Path=C:\Program Files(x86)\Steam\steam.exe
Icon4Path=C:\Riot Games\League of Legends\LeagueClient.exe
Icon5Path=photoshop.exe
Icon6Path=www.deviantart.com
Icon7Path=C:\ProgramData\ervan\Microsoft\Teams\Update.exe
Icon8Path=https://app.mystudylife.com/calendar

;;----------Icons Directories----------

Icon1Name=C:\Users\ervan\Documents\Rainmeter\Skins\ClockWorld\@Resources\Particles\Desktop Shortcuts\spotify.png  
Icon2Name=C:\Users\ervan\Documents\Rainmeter\Skins\ClockWorld\@Resources\Particles\Desktop Shortcuts\edge.png
Icon3Name=#@#Particles\Desktop Shortcuts\steam.png
Icon4Name=C:\Users\ervan\Documents\Rainmeter\Skins\ClockWorld\@Resources\Particles\Desktop Shortcuts\league.png
Icon5Name=#@#Particles\Desktop Shortcuts\photoshop.png
Icon6Name=#@#Particles\Desktop Shortcuts\deviantart.png
Icon7Name=C:\Users\ervan\Desktop\Icons\Microsoft Teams.png
Icon8Name=C:\Users\ervan\Desktop\Icons\MyStudyLife.png

;;----------Adaptive Colors----------

MColor=157,101,130
NColor=72,119,135
AColor=85,145,107
EColor=255,127,80
NTColor=136,51,110

;;----------Others----------

Language=en-US
Accent=85,145,107
ClipString=460.8







;;----------Music Player Data (*)----------

AudioPlayerName=WebPlayer
Music=WebNowPlaying.dll



(*) BACKUP BEFORE CHANGING VALUES

