[Variables]
Author=Evans Stenakis
Name=Variables
Version=Summer 2020
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0

;;--------------------------------------------


BE CAREFUL NOT TO CHANGE THE VARIABLES NAMES


;;----------Profile picture and name----------

UserImagePath=#@#Particles\User\Icon.jpg
UserName=%username%

;;----------Wallpapers Directories----------

MorningWP=#@#Wallpapers\Morning.jpg
NoonWP=#@#Wallpapers\Noon.jpg
AfternoonWP=#@#Wallpapers\Afternoon.jpg
EveningWP=#@#Wallpapers\Evening.jpg
NightWP=#@#Wallpapers\Night.jpg

;;----------Time Stamps----------

MorningHour=06
NoonHour=12
AfternoonHour=16
EveningHour=20
NightHour=23

;;----------Quotes----------

Morning=Good Morning
Noon=Good Noon
Afternoon=Good Afternoon
Evening=Good Evening
Night=Good Night

;;----------Shortcuts Directories----------

Icon1Path=C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Icon2Path=C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
Icon3Path=C:\Program Files (x86)\Steam\steam.exe
Icon4Path=photoshop.exe
Icon5Path=photoshop.exe
Icon6Path=www.deviantart.com
Icon7Path=C:\Users\ervan\AppData\Roaming\Spotify\Spotify.exe
Icon8Path=winword.exe

;;----------Icons Directories----------

Icon1Name=chrome.png  
Icon2Name=edge.png
Icon3Name=steam.png
Icon4Name=photoshop.png
Icon5Name=#@#Particles\Desktop Shortcuts\photoshop.png
Icon6Name=deviantart.png
Icon7Name=spotify.png
Icon8Name=word.png

;;----------Adaptive Colors----------

MColor=157,101,130
NColor=71,118,134
AColor=85,145,107
EColor=255,127,80
NTColor=136,51,110

;;----------Others----------

Language=en-US
Accent=136,51,110
ClipString=460.8







;;----------Music Player Data (*)----------

AudioPlayerName=Spotify
Music=WebNowPlaying.dll



(*) BACKUP BEFORE CHANGING VALUES

