[MeterShadowBar0]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed42
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar1]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed41
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar2]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed40
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar3]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed39
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar4]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed38
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar5]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed37
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar6]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed36
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar7]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed35
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar8]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed34
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar9]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed33
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar10]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed32
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar11]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed31
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar12]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed30
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar13]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed29
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar14]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed28
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar15]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed27
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar16]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed26
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar17]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed25
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar18]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed24
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar19]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed23
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar20]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed22
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar21]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed21
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar22]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed20
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar23]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed19
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar24]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed18
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar25]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed17
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar26]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed16
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar27]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed15
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar28]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed14
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar29]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed13
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar30]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed12
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar31]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed11
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar32]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed10
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar33]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed9
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar34]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed8
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar35]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed7
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar36]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed6
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar37]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed5
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar38]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed4
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar39]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed3
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar40]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed2
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar41]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed1
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)
[MeterShadowBar42]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed0
TransformationMatrix=[Matrix]
Hidden=(0 > 0 ? 0 : 1)