[Variables]

; (Do not contain "(Title)" in the translation)
; If your language contains one or all of those, leave the word unchanged.
; This section contains data that their font does not support punctuations and special characters.

About=
Alarm0=
Attention!=Atención
Available=Disponible
Browse files=
Changing quotes will override current quotes in file=
ClipString=
Clock (Title)=Reloj
Clock=Reloj
Connecting to server...=Conectando al servidor...
Connection error=Error de conexión
Coordinates=Coordenadas
Could not find the specified location=
Couldn't access server=No se pudo acceder al servidor
Current backup is placed in Rainmeter/Skins/@Vault=Copia de seguridad actual en Rainmeter/Skins/@Vault
Current=Actual
Custom file=
Custom icon=
Disclaimer=
Download=Descargar
GoodAfternoon=Buenas Tardes
GoodEvening=Buenas Tardes
GoodMorning=Buenos Dias
GoodNight=Buenas Noches
GoodNoon=Bueno Mediodia
Hidden=Oculto
If weather does not load, restart Rainmeter=Si el tiempo no se carga, reinicie el Rainmeter
Location error=Error de localización
Location0=
Name0=Nombre
Persistent media controls=Controles de medios persistentes
Picture=Imagen
Player (Title)=Jugador
Player=Jugador
Please check your internet connection=
Profile (Title)=Perfil
Profile=Perfil
Progress bar=Barra de progreso
Quotes font=
Restart=Reiniciar
Restore previous version (Temporarily disabled)=
Shortcuts (Title)=Atajos
Shortcuts=Atajos
Skin language=
Skin size multiplier=
Suggested values=Valores sugeridos
System (Title)=Sistema
System=Sistema
Temperature unit=Temperature unit
This page does not exist (yet)=This page does not exist (yet)
Updates=Actualizaciones
Using dev version=
Wallpapers=
Weather (Title)=Clima
Weather=Clima
You're up to date=Estás actualizado