;Welcome to the ClockWorld Translation Contribution (CTC) service

;Translate as much as you can.
;Provide the language of translation below.
;Do not include "_","0" or any other non-character symbol in your translation.
;Make sure to provide separate words for multiple word variables.
;Be careful not to change the variables' names.
;If your langauge contains non-latin characters (Russian, Indian etc.) make sure to encode it as "UTF-16LE". (File > Save As => Encoding)
;Do not translate sentences that start with a semicolon (;) - like this one.

;Upload the final file here: https://forms.gle/TmbYcLn3wMW2bhDc9


;I AM TRANSLATING IN:

[Variables]
;Single variables
AddTranslation=
Afternoon=
Angle_=
Animations=
BarHeight_=
BarNumber=
Big=
CheckForUpdates=
Classic=
ClipString=
Clock=
ClockFormat=
ColorScheme=
Current=
Dark=
DayFormat=
Download=
Evening=
File=
Format=
GoodAfternoon=
GoodEvening=
GoodMorning=
GoodNight=
GoodNoon=
Guide=
Hidden=
Icon_=
Language=
Light=
Line=
Long=
Medium=
MonthFormat=
Morning=
Name0=
Night=
Noon=
Note=
NowPlaying=
NumberOfShortcuts=
OK=
Pairs=
Picture=
Player=
Profile=
ProgressBar=
Reset=
Restart=
Retry=
Sensitivity_=
Short=
Shortcuts=
Shutdown=
SkinSize=
SleepMode=
Small=
Smoothness=
System=
TimeStamps=
Theme=
Width=
Visualizer=
Updates=

;Phrases
By clicking the "+" button the "Open..." menu will pop up. From there, select the file you want to open with this shortcut.=
By clicking the "+" button the "Open..." menu will pop up. From there, select the icon you want to represent this shortcut.=
Connecting to GitHub...=
Couldn't access Github=
Do you wish to put your computer to sleep?=
Do you wish to restart your computer?=
Do you wish to shut down your computer?=
Games from gaming platforms cannot be launched separately. (ex. Steam, Epic Games)=
Is available!=
PersistentMediaControls=
Up to date=
Using Dev Version=